server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lojalivros
    username: postgres
    password: 1234
  jpa:
    database-plataform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    defer-datasource-initialization: true
